settings:
  allowGlow: true
  broadcastTags: true
  preventTagBack: true
  gameTime: 600
  powerUpInterval: 120

game-modes:
  classic:
    enabled: true
    description: "Classic tag game mode"
  freeze:
    enabled: true
    description: "Freeze tag mode - tagged players are frozen until unfrozen"
  team:
    enabled: true
    description: "Team tag mode - players are split into teams"
