name: TagGame
version: '${project.version}'
main: com.ChickenWithACrown.tag.TagGame
api-version: '1.21'
authors: [ChickenWithACrown]
description: A versatile Minecraft tag game plugin
commands:
  tag:
    description: Main command for the Tag Game plugin
    usage: /<command> [help|join|leave|start|stop|it|score|setleaderboard|mode|setmap|autostart|list]
    aliases: [taggame, tag]

permissions:
  tag.admin:
    description: Gives access to all admin commands
    default: op
  tag.admin.start:
    description: Allows starting games
    default: op
  tag.admin.stop:
    description: Allows stopping games
    default: op
  tag.admin.setmap:
    description: Allows setting maps
    default: op
  tag.admin.mode:
    description: Allows changing game modes
    default: op
  tag.admin.setleaderboard:
    description: Allows creating leaderboards
    default: op
  tag.admin.autostart:
    description: Allows toggling auto-start
    default: op
  tag.player.join:
    description: Join the tag game
    default: true
  tag.player.leave:
    description: Leave the tag game
    default: true
  tag.player.viewit:
    description: View who is 'It'
    default: true
